[package]
name = "dioxus-code-docsite"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Demo application for dioxus-code."
repository.workspace = true
keywords.workspace = true
categories.workspace = true
publish = false

[dependencies]
dioxus = { version = "=0.8.0-alpha.0", features = ["router"] }
dioxus-code = { workspace = true, features = ["detection", "detectable-languages"] }
dioxus-code-editor = { workspace = true, features = ["detection", "detectable-languages"] }
dioxus-primitives = { git = "https://github.com/DioxusLabs/components", branch = "0.8", default-features = false, features = ["router"] }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
web = ["dioxus/web", "dioxus-primitives/web"]
fullstack = ["dioxus/fullstack"]
server = ["dioxus/server", "dioxus/fullstack"]

[[example]]
name = "snippet-starter"
path = "snippets/starter.rs"

[[example]]
name = "snippet-demo"
path = "snippets/demo.rs"

[[example]]
name = "snippet-runtime"
path = "snippets/runtime.rs"

[[example]]
name = "snippet-static-macro"
path = "snippets/static_macro.rs"

[[example]]
name = "snippet-example"
path = "snippets/example.rs"

[[example]]
name = "snippet-palette"
path = "snippets/palette.rs"
