[package]
name = "dioxus-code-macro"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Compile-time syntax highlighting macro for dioxus-code."
repository.workspace = true
homepage.workspace = true
keywords.workspace = true
categories.workspace = true
readme = "README.md"

[lib]
proc-macro = true

[dependencies]
arborium = { version = "2.16.0", default-features = false, features = ["all-languages"] }
arborium-theme = "2.16.0"
macro-string = "0.1.4"
proc-macro-crate = "3.5.0"
proc-macro2 = "1.0.103"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
