[package]
name = "dioxus-code-basic"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "Basic dioxus-code example application."
repository.workspace = true
keywords.workspace = true
categories.workspace = true

[dependencies]
dioxus = { version = "0.7.0" }
dioxus-code = { workspace = true, features = ["runtime"] }

[features]
default = ["desktop"]
desktop = ["dioxus/desktop"]
