name: GitHub Pages

on:
  push:
    branches: [main]
  schedule:
    - cron: "42 8 * * *"
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-deploy:
    uses: ealmloff/dioxus-ci/.github/workflows/deploy-gh-pages.yml@main
    with:
      working-directory: docsite
      ssg: true
      no-default-features: true
      features: fullstack
      debug-symbols: false
      dx-cli-version: 0.7.7
