name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
    branches: [main]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ealmloff/dioxus-ci/.github/workflows/check.yml@main
    with:
      all-features: false
      no-default-features: true
      features: dioxus-code/all-languages dioxus-code-editor/web dioxus-code-docsite/web dioxus-code-live-input/web

  test:
    uses: ealmloff/dioxus-ci/.github/workflows/test.yml@main
    with:
      no-default-features: true
      features: dioxus-code/all-languages dioxus-code-editor/web dioxus-code-docsite/web dioxus-code-live-input/web

  fmt:
    uses: ealmloff/dioxus-ci/.github/workflows/fmt.yml@main

  docs:
    uses: ealmloff/dioxus-ci/.github/workflows/docs.yml@main
    with:
      all-features: false
      no-default-features: true
      features: dioxus-code/all-languages dioxus-code-editor/web dioxus-code-docsite/web dioxus-code-live-input/web

  clippy:
    uses: ealmloff/dioxus-ci/.github/workflows/clippy.yml@main
    with:
      all-features: false
      no-default-features: true
      features: dioxus-code/all-languages dioxus-code-editor/web dioxus-code-docsite/web dioxus-code-live-input/web

  web-demo:
    if: github.event_name == 'push'
    uses: ealmloff/dioxus-ci/.github/workflows/web-build.yml@main
    with:
      working-directory: docsite
      ssg: true
      no-default-features: true
      features: fullstack
      debug-symbols: false
      base-path: ${{ github.event.repository.name }}
      dx-cli-version: 0.7.7
